[package]
name                  = "veryl-analyzer"
version               = "0.14.1"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition.workspace     = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash          = {workspace = true}
itertools       = "0.14.0"
smallvec        = {workspace = true}
strnum_bitwidth = {workspace = true}
thiserror       = {workspace = true}
veryl-metadata  = {version = "0.14.1", path = "../metadata"}
veryl-parser    = {version = "0.14.1", path = "../parser"}
daggy           = "0.8.1"
bimap           = "0.6.3"

[target.'cfg(target_family = "wasm")'.dependencies]
miette          = {workspace = true, features = ["fancy-no-syscall"]}

[target.'cfg(not(target_family = "wasm"))'.dependencies]
miette          = {workspace = true, features = ["fancy"]}

[dev-dependencies]
toml = {workspace = true}
