name = "Veryl"
grammar = "veryl"
path_suffixes = ["veryl"]
line_comments = ["// "]

brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = false, newline = true, not_in = [
        "string",
        "comment",
    ] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "`", end = "`", close = true, newline = false, not_in = [
        "string",
    ] },
]
