[package]
name = "veryl-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parol_runtime = {version = "0.9.0", features = ["auto_generation"]}
regex         = "1.7.0"

[build-dependencies]
parol   = "0.14.0"
walkdir = "2.3.2"
