[package]
name                  = "mdbook-veryl"
version               = "0.5.5"
authors.workspace     = true
repository.workspace  = true
keywords.workspace    = true
categories.workspace  = true
license.workspace     = true
readme.workspace      = true
description.workspace = true
edition               = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow         = {workspace = true}
clap           = {workspace = true}
line-col       = "0.2.1"
mdbook         = "0.4.28"
pulldown-cmark = "0.9.2"
regex          = {workspace = true}
semver         = {workspace = true}
serde_json     = {workspace = true}
veryl-parser   = {version = "0.5.5", path = "../parser"}
